//
//  FriendsList.swift
//  Netmate
//
//  Created by GiN Eugene on 26/7/2022.
//

import UIKit

struct Friend {
    let avatar: UIImage
    let firstName: String
    let lastName: String
    let profession: String
    let photo: [Photo]
    let feed: [Feed]
}

struct Feed {
    let avatar: UIImage
    let firstName: String
    let lastName: String
    let profession: String
    let post: Post
}

struct Post {
    let article: String
    let image: UIImage
}

struct FriendsSection {
    let friends: [Friend]
}

class FriendsStorage {
    static let tableModel = [
        FriendsSection(friends: [
            Friend(avatar: #imageLiteral(resourceName: "Margot_Robbie_2"),
                   firstName: "Margot",
                   lastName: "Robbie",
                   profession: "Actress, model",
                   photo: [Photo(image: #imageLiteral(resourceName: "bmw")), Photo(image: #imageLiteral(resourceName: "beach")), Photo(image: #imageLiteral(resourceName: "dog-")), Photo(image: #imageLiteral(resourceName: "ocean")), Photo(image: #imageLiteral(resourceName: "zakynthos")), Photo(image: #imageLiteral(resourceName: "cat")), Photo(image: #imageLiteral(resourceName: "woman2")), Photo(image: #imageLiteral(resourceName: "drop")),Photo(image: #imageLiteral(resourceName: "women")), Photo(image: #imageLiteral(resourceName: "jellyfish")), Photo(image: #imageLiteral(resourceName: "smoothie")), Photo(image: #imageLiteral(resourceName: "strawberries")), Photo(image: #imageLiteral(resourceName: "girl-26")), Photo(image: #imageLiteral(resourceName: "kingfisher")), Photo(image: #imageLiteral(resourceName: "man")), Photo(image: #imageLiteral(resourceName: "sailboat")),Photo(image: #imageLiteral(resourceName: "sea-shell")), Photo(image: #imageLiteral(resourceName: "car2"))],
                   feed: [
                    Feed(avatar: #imageLiteral(resourceName: "Margot_Robbie_2"), firstName: "Margot", lastName: "Robbie", profession: "Actress, model", post: Post(article: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: #imageLiteral(resourceName: "Margot_Robbie_2"))),
                    Feed(avatar: #imageLiteral(resourceName: "Margot_Robbie_2"), firstName: "Margot", lastName: "Robbie", profession: "Actress, model", post: Post(article: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: #imageLiteral(resourceName: "Margot_Robbie_2"))),
                    Feed(avatar: #imageLiteral(resourceName: "Margot_Robbie_2"), firstName: "Margot", lastName: "Robbie", profession: "Actress, model", post: Post(article: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: #imageLiteral(resourceName: "Margot_Robbie_2")))]),
            Friend(avatar: #imageLiteral(resourceName: "Elon_Mask"),
                   firstName: "Elon",
                   lastName: "Mask",
                   profession: "FRS, business magnate and investor",
                   photo: [Photo(image: #imageLiteral(resourceName: "macroperspective")), Photo(image: #imageLiteral(resourceName: "ferrari-458-spider")), Photo(image: #imageLiteral(resourceName: "cat")), Photo(image: #imageLiteral(resourceName: "wolf")), Photo(image: #imageLiteral(resourceName: "tasmanian-devil")), Photo(image: #imageLiteral(resourceName: "palm-trees")),Photo(image: #imageLiteral(resourceName: "shoes")), Photo(image: #imageLiteral(resourceName: "sea-25")), Photo(image: #imageLiteral(resourceName: "surf-15")), Photo(image: #imageLiteral(resourceName: "road")), Photo(image: #imageLiteral(resourceName: "porsche")), Photo(image: #imageLiteral(resourceName: "waves")), Photo(image: #imageLiteral(resourceName: "girls")), Photo(image: #imageLiteral(resourceName: "tree"))],
                   feed: [
                    Feed(avatar: #imageLiteral(resourceName: "Elon_Mask"), firstName: "Elon", lastName: "Mask", profession: "FRS, business magnate and investor", post: Post(article: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: #imageLiteral(resourceName: "Elon_Mask"))),
                    Feed(avatar: #imageLiteral(resourceName: "Elon_Mask"), firstName: "Elon", lastName: "Mask", profession: "FRS, business magnate and investor", post: Post(article: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: #imageLiteral(resourceName: "Elon_Mask"))),
                    Feed(avatar: #imageLiteral(resourceName: "Elon_Mask"), firstName: "Elon", lastName: "Mask", profession: "FRS, business magnate and investor", post: Post(article: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: #imageLiteral(resourceName: "Elon_Mask")))]),
            Friend(avatar: #imageLiteral(resourceName: "Gal_Gadot"),
                   firstName: "Gal",
                   lastName: "Gadot",
                   profession: "Actress, model",
                   photo: [Photo(image: #imageLiteral(resourceName: "ladybug")), Photo(image: #imageLiteral(resourceName: "raccoon")), Photo(image: #imageLiteral(resourceName: "dog-2")), Photo(image: #imageLiteral(resourceName: "zakynthos")), Photo(image: #imageLiteral(resourceName: "face-painting")), Photo(image: #imageLiteral(resourceName: "boat")), Photo(image: #imageLiteral(resourceName: "girls")), Photo(image: #imageLiteral(resourceName: "milky-way")), Photo(image: #imageLiteral(resourceName: "waves")), Photo(image: #imageLiteral(resourceName: "the-sun"))],
                   feed: [
                    Feed(avatar: #imageLiteral(resourceName: "Gal_Gadot"), firstName: "Gal", lastName: "Gadot", profession: "Actress, model", post: Post(article: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: #imageLiteral(resourceName: "Gal_Gadot"))),
                    Feed(avatar: #imageLiteral(resourceName: "Gal_Gadot"), firstName: "Gal", lastName: "Gadot", profession: "Actress, model", post: Post(article: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: #imageLiteral(resourceName: "Gal_Gadot"))),
                    Feed(avatar: #imageLiteral(resourceName: "Gal_Gadot"), firstName: "Gal", lastName: "Gadot", profession: "Actress, model", post: Post(article: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: #imageLiteral(resourceName: "Gal_Gadot")))]),
            Friend(avatar: #imageLiteral(resourceName: "Neil _deGrasse _Tyson"),
                   firstName: "Neil deGrasse",
                   lastName: "Tyson",
                   profession: "Astrophysicist, science communicator",
                   photo: [Photo(image: #imageLiteral(resourceName: "jellyfish")), Photo(image: #imageLiteral(resourceName: "smoothie")), Photo(image: #imageLiteral(resourceName: "strawberries")), Photo(image: #imageLiteral(resourceName: "girl-26")), Photo(image: #imageLiteral(resourceName: "kingfisher")), Photo(image: #imageLiteral(resourceName: "man")), Photo(image: #imageLiteral(resourceName: "sailboat")),Photo(image: #imageLiteral(resourceName: "sea-shell")), Photo(image: #imageLiteral(resourceName: "car2"))],
                   feed: [
                    Feed(avatar: #imageLiteral(resourceName: "Neil _deGrasse _Tyson"), firstName: "Neil deGrasse", lastName: "Tyson", profession: "Astrophysicist, science communicator", post: Post(article: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: #imageLiteral(resourceName: "Neil _deGrasse _Tyson"))),
                    Feed(avatar: #imageLiteral(resourceName: "Neil _deGrasse _Tyson"), firstName: "Neil deGrasse", lastName: "Tyson", profession: "Astrophysicist, science communicator", post: Post(article: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: #imageLiteral(resourceName: "Neil _deGrasse _Tyson"))),
                    Feed(avatar: #imageLiteral(resourceName: "Neil _deGrasse _Tyson"), firstName: "Neil deGrasse", lastName: "Tyson", profession: "Astrophysicist, science communicator", post: Post(article: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: #imageLiteral(resourceName: "Neil _deGrasse _Tyson")))]),
            Friend(avatar: #imageLiteral(resourceName: "Dwaine_Johnson"),
                   firstName: "Dwaine",
                   lastName: "Johnson",
                   profession: "Actor, professional wrestler",
                   photo: [Photo(image: #imageLiteral(resourceName: "bmw")), Photo(image: #imageLiteral(resourceName: "beach")), Photo(image: #imageLiteral(resourceName: "dog-")), Photo(image: #imageLiteral(resourceName: "ocean")), Photo(image: #imageLiteral(resourceName: "zakynthos")), Photo(image: #imageLiteral(resourceName: "cat")), Photo(image: #imageLiteral(resourceName: "woman2")), Photo(image: #imageLiteral(resourceName: "drop")),Photo(image: #imageLiteral(resourceName: "women"))],
                   feed: [
                    Feed(avatar: #imageLiteral(resourceName: "Dwaine_Johnson"), firstName: "Dwaine", lastName: "Johnson", profession: "Actor, professional wrestler", post: Post(article: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: #imageLiteral(resourceName: "Dwaine_Johnson"))),
                    Feed(avatar: #imageLiteral(resourceName: "Dwaine_Johnson"), firstName: "Dwaine", lastName: "Johnson", profession: "Actor, professional wrestler", post: Post(article: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: #imageLiteral(resourceName: "Dwaine_Johnson"))),
                    Feed(avatar: #imageLiteral(resourceName: "Dwaine_Johnson"), firstName: "Dwaine", lastName: "Johnson", profession: "Actor, professional wrestler", post: Post(article: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: #imageLiteral(resourceName: "Dwaine_Johnson")))]),
            Friend(avatar: #imageLiteral(resourceName: "Anya _Chalotra"),
                   firstName: "Anya",
                   lastName: "Chalotra",
                   profession: "Actress",
                   photo: [Photo(image: #imageLiteral(resourceName: "jellyfish")), Photo(image: #imageLiteral(resourceName: "smoothie")), Photo(image: #imageLiteral(resourceName: "strawberries")), Photo(image: #imageLiteral(resourceName: "girl-26")), Photo(image: #imageLiteral(resourceName: "kingfisher")), Photo(image: #imageLiteral(resourceName: "man")), Photo(image: #imageLiteral(resourceName: "sailboat")),Photo(image: #imageLiteral(resourceName: "sea-shell")), Photo(image: #imageLiteral(resourceName: "car2"))],
                   feed: [
                    Feed(avatar: #imageLiteral(resourceName: "Anya _Chalotra"), firstName: "Anya", lastName: "Chalotra", profession: "Actress", post: Post(article: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: #imageLiteral(resourceName: "Anya _Chalotra"))),
                    Feed(avatar: #imageLiteral(resourceName: "Anya _Chalotra"), firstName: "Anya", lastName: "Chalotra", profession: "Actress", post: Post(article: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: #imageLiteral(resourceName: "Anya _Chalotra"))),
                    Feed(avatar: #imageLiteral(resourceName: "Anya _Chalotra"), firstName: "Anya", lastName: "Chalotra", profession: "Actress", post: Post(article: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: #imageLiteral(resourceName: "Anya _Chalotra")))]),
            Friend(avatar: #imageLiteral(resourceName: "Tom_Cruise"),
                   firstName: "Tom",
                   lastName: "Cruise",
                   profession: "Actor, producer",
                   photo: [Photo(image: #imageLiteral(resourceName: "jellyfish")), Photo(image: #imageLiteral(resourceName: "smoothie")), Photo(image: #imageLiteral(resourceName: "strawberries")), Photo(image: #imageLiteral(resourceName: "girl-26")), Photo(image: #imageLiteral(resourceName: "kingfisher")), Photo(image: #imageLiteral(resourceName: "man")), Photo(image: #imageLiteral(resourceName: "sailboat")),Photo(image: #imageLiteral(resourceName: "sea-shell")), Photo(image: #imageLiteral(resourceName: "car2"))],
                   feed: [
                    Feed(avatar: #imageLiteral(resourceName: "Tom_Cruise"), firstName: "Tom", lastName: "Cruise", profession: "Actor, producer", post: Post(article: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: #imageLiteral(resourceName: "Tom_Cruise"))),
                    Feed(avatar: #imageLiteral(resourceName: "Tom_Cruise"), firstName: "Tom", lastName: "Cruise", profession: "Actor, producer", post: Post(article: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: #imageLiteral(resourceName: "Tom_Cruise"))),
                    Feed(avatar: #imageLiteral(resourceName: "Tom_Cruise"), firstName: "Tom", lastName: "Cruise", profession: "Actor, producer", post: Post(article: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: #imageLiteral(resourceName: "Tom_Cruise")))]
                  )])
    ]
}
